"use client";

import { FormEvent, useEffect, useState } from "react";

type Tab = "price" | "season" | "history" | "settings";
type Unit = "kg" | "g";
type Language = "ko" | "en" | "ja" | "zh";
type Quote = { basePerKg: number; message: string };
type Log = { fish: string; amount: number; unit: Unit; origin: "farmed" | "wild"; low: number; high: number; at: string; marketNote: string };

const prices: Record<string, number> = { "광어": 20000, "고등어": 6500, "갈치": 28000, "참돔": 25000, "다금바리": 85000, "민어": 30000, "연어": 22000, "우럭": 12000, "전복": 42000, "꽃게": 18000, "전어": 11000, "대게": 38000, "방어": 26000, "삼치": 9000, "농어": 22000, "대구": 12500, "아귀": 14000, "참치": 45000, "랍스터": 65000 };
const seasonal: Record<number, [string, number][]> = { 1:[["굴",9000],["대게",38000],["방어",26000],["꼬막",18000]], 2:[["꼬막",18000],["삼치",9000],["아귀",14000],["대구",12500]], 3:[["주꾸미",15000],["쭈꾸미",15000],["도다리",21000],["멍게",9000]], 4:[["멍게",9000],["바지락",6000],["도다리",21000],["갑오징어",16500]], 5:[["병어",23000],["갑오징어",16500],["민어",30000],["다금바리",85000]], 6:[["장어",20000],["민어",30000],["농어",22000],["전복",42000]], 7:[["민어",30000],["전복",42000],["장어",20000],["한치",18000]], 8:[["민어",30000],["우럭",12000],["전복",42000],["다금바리",85000],["갈치",28000]], 9:[["전어",11000],["꽃게",18000],["갈치",28000],["고등어",6500]], 10:[["고등어",6500],["갈치",28000],["광어",20000],["전어",11000]], 11:[["광어",20000],["굴",9000],["대구",12500],["방어",26000]], 12:[["대구",12500],["굴",9000],["방어",26000],["대게",38000]] };

const labels: Record<Language, Record<string, string>> = {
  ko: { price:"적정 가격 확인", season:"제철 물고기", history:"가격 기록", settings:"설정", fish:"생선 이름", fishHint:"예: 광어, 고등어, 다금바리", weight:"무게", production:"생산 방식", farmed:"양식", wild:"자연산", check:"적정가 확인 →", checking:"당일 경매가 확인 중…", estimated:"예상 적정 구매가", youtube:"YouTube 손질 영상 보기 ↗", notice:"살 때 확인할 점", market:"당일 경매가 × 소매 보정계수(1.2~1.5배)를 적용했어요.", date:"기기 날짜 기준", seasonal:"제철 추천 수산물", clear:"전체 기록 삭제", retain:"기록은 최대 1년 동안 보관됩니다.", empty:"아직 가격 기록이 없습니다.", language:"언어", report:"버그 및 제보사항", choose:"앱 언어 선택", back:"‹ 뒤로", send:"제보 저장", reportHint:"불편한 점이나 오류를 자세히 적어주세요.", saved:"제보 내용을 이 기기에 저장했어요.", current:"현재 선택" },
  en: { price:"Fair price", season:"In season", history:"History", settings:"Settings", fish:"Fish name", fishHint:"e.g. flounder, mackerel", weight:"Weight", production:"Source", farmed:"Farmed", wild:"Wild", check:"Check fair price →", checking:"Checking today's auction…", estimated:"Estimated fair price", youtube:"Watch cleaning video on YouTube ↗", notice:"Before you buy", market:"Today's auction price × retail adjustment (1.2–1.5×).", date:"Based on your device date", seasonal:"Seasonal seafood", clear:"Clear all history", retain:"History is kept for up to one year.", empty:"No saved price records yet.", language:"Language", report:"Bug report & feedback", choose:"Choose app language", back:"‹ Back", send:"Save report", reportHint:"Describe a bug or suggestion in detail.", saved:"Your report was saved on this device.", current:"Selected" },
  ja: { price:"適正価格", season:"旬の魚", history:"履歴", settings:"設定", fish:"魚の名前", fishHint:"例：ヒラメ、サバ", weight:"重さ", production:"生産方法", farmed:"養殖", wild:"天然", check:"適正価格を確認 →", checking:"本日の競り値を確認中…", estimated:"予想適正購入価格", youtube:"YouTubeでさばき方を見る ↗", notice:"購入前の確認", market:"当日の競り値 × 小売補正係数（1.2〜1.5倍）です。", date:"端末の日付基準", seasonal:"旬の水産物", clear:"履歴をすべて削除", retain:"履歴は最大1年間保存されます。", empty:"価格履歴はまだありません。", language:"言語", report:"不具合・お問い合わせ", choose:"アプリの言語", back:"‹ 戻る", send:"送信内容を保存", reportHint:"不具合やご意見を詳しく書いてください。", saved:"この端末に保存しました。", current:"選択中" },
  zh: { price:"合理价格", season:"当季海鲜", history:"记录", settings:"设置", fish:"鱼类名称", fishHint:"例如：比目鱼、鲭鱼", weight:"重量", production:"养殖方式", farmed:"养殖", wild:"野生", check:"查询合理价格 →", checking:"正在查询今日拍卖价…", estimated:"预计合理购买价", youtube:"在 YouTube 查看处理视频 ↗", notice:"购买前检查", market:"已采用当日拍卖价 × 零售调整系数（1.2～1.5倍）。", date:"以设备日期为准", seasonal:"当季推荐海鲜", clear:"清除全部记录", retain:"记录最多保存一年。", empty:"暂无价格记录。", language:"语言", report:"错误与反馈", choose:"选择应用语言", back:"‹ 返回", send:"保存反馈", reportHint:"请详细描述问题或建议。", saved:"反馈已保存在此设备。", current:"已选择" }
};

const care: Record<string, string[]> = {
  "고등어": ["눈이 맑고 아가미가 선홍색인지 확인하세요.", "비린내보다 시큼하거나 암모니아 냄새가 나면 피하세요.", "구매 후 바로 냉장하고, 하루 안에 조리하는 것이 좋아요.", "내장은 빨리 제거해야 살이 무르는 것을 줄일 수 있어요."],
  "갈치": ["은빛 비늘이 고르고 몸통에 탄력이 있는지 보세요.", "표면이 지나치게 마르거나 누렇게 변한 것은 피하세요.", "토막 구매 시 단면이 투명하고 물이 많이 나오지 않는지 확인하세요.", "냉장 보관은 짧게 하고 장기 보관은 소분해 냉동하세요."],
  "광어": ["살이 투명하고 탄력이 있으며 핏물이 과하지 않은지 보세요.", "회로 먹을 때는 활어 상태와 손질 시간을 확인하세요.", "포장 회는 차갑게 유지되고 소비기한이 충분한지 확인하세요.", "구매 후에는 냉장 보관하고 가능한 당일 드세요."],
  "연어": ["주황색이 지나치게 진하거나 가장자리가 마른 제품은 피하세요.", "생식용인지, 냉장·냉동 이력이 어떤지 확인하세요.", "포장 안에 물이 많이 고이면 신선도가 떨어질 수 있어요.", "개봉 후에는 바로 먹고 남은 것은 밀봉 냉장하세요."],
  "전복": ["살아 있는 전복은 껍데기에 단단히 붙어 있고 촉수가 움직여요.", "껍데기 가장자리가 깨졌거나 냄새가 강하면 피하세요.", "구매 후 해감물에 오래 두지 말고 빠르게 손질하세요.", "생식보다 충분히 익혀 먹는 것이 안전해요."],
  "꽃게": ["들었을 때 묵직하고 다리가 빠지지 않은 것을 고르세요.", "배딱지가 단단하고 비린내 외의 이상한 냄새가 없는지 보세요.", "활게는 차갑게 유지하고 가능한 빨리 조리하세요.", "알레르기가 있다면 갑각류 섭취에 주의하세요."],
  "default": ["눈이 맑고 아가미가 붉으며 살에 탄력이 있는지 확인하세요.", "시큼한 냄새, 암모니아 냄새, 지나친 점액이 있으면 구매하지 마세요.", "원산지·양식 여부·중량·단가를 결제 전에 다시 확인하세요.", "구매 후에는 차갑게 보관하고 가능한 당일 또는 다음 날 조리하세요."]
};

const fishNames: Record<Language, Record<string, string>> = {
  ko: {},
  en: { "광어": "Flounder", "고등어": "Mackerel", "갈치": "Hairtail", "참돔": "Red sea bream", "다금바리": "Giant grouper", "민어": "Brown croaker", "연어": "Salmon", "우럭": "Rockfish", "전복": "Abalone", "꽃게": "Blue crab", "대게": "Snow crab", "방어": "Yellowtail", "삼치": "Spanish mackerel", "농어": "Sea bass", "대구": "Cod", "아귀": "Monkfish", "참치": "Tuna", "랍스터": "Lobster" },
  ja: { "광어": "ヒラメ", "고등어": "サバ", "갈치": "タチウオ", "참돔": "マダイ", "다금바리": "タマカイ", "민어": "ニベ", "연어": "サーモン", "우럭": "メバル", "전복": "アワビ", "꽃게": "ワタリガニ", "대게": "ズワイガニ", "방어": "ブリ", "삼치": "サワラ", "농어": "スズキ", "대구": "タラ", "아귀": "アンコウ", "참치": "マグロ", "랍스터": "ロブスター" },
  zh: { "광어": "比目鱼", "고등어": "鲭鱼", "갈치": "带鱼", "참돔": "真鲷", "다금바리": "龙胆石斑鱼", "민어": "黄花鱼", "연어": "三文鱼", "우럭": "岩鱼", "전복": "鲍鱼", "꽃게": "梭子蟹", "대게": "雪蟹", "방어": "鰤鱼", "삼치": "马鲛鱼", "농어": "海鲈鱼", "대구": "鳕鱼", "아귀": "安康鱼", "참치": "金枪鱼", "랍스터": "龙虾" }
};
const translatedCare: Record<Exclude<Language, "ko">, string[]> = {
  en: ["Check that the eyes are clear, the gills are red, and the flesh is firm.", "Avoid seafood with sour, ammonia-like, or unusually strong odors.", "Confirm origin, farming method, weight, and unit price before paying.", "Keep it cold after purchase and cook it the same day or the next day."],
  ja: ["目が澄み、えらが赤く、身に弾力があるか確認してください。", "酸っぱいにおい、アンモニア臭、強い異臭があるものは避けてください。", "会計前に原産地・養殖／天然・重量・単価を再確認してください。", "購入後は低温で保管し、当日または翌日に調理してください。"],
  zh: ["请确认鱼眼清澈、鱼鳃鲜红且鱼肉有弹性。", "有酸味、氨味或异常强烈气味的海鲜不要购买。", "付款前请再次确认产地、养殖方式、重量和单价。", "购买后应低温保存，并在当天或次日烹饪。"]
};
const displayFish = (name: string, language: Language) => fishNames[language][name] || name;
const displayCare = (name: string, language: Language) => language === "ko" ? (care[name] || care.default) : translatedCare[language];

const won = (value: number) => `₩${(Math.round(value / 100) * 100).toLocaleString()}`;

export default function Home() {
  const [tab, setTab] = useState<Tab>("price");
  const [view, setView] = useState<"main" | "language" | "report">("main");
  const [language, setLanguage] = useState<Language>("ko");
  const [fish, setFish] = useState("광어"); const [unit, setUnit] = useState<Unit>("kg"); const [amount, setAmount] = useState(1); const [origin, setOrigin] = useState<"farmed" | "wild">("farmed");
  const [result, setResult] = useState<Log | null>(null); const [history, setHistory] = useState<Log[]>([]); const [loading, setLoading] = useState(false); const [report, setReport] = useState(""); const [saved, setSaved] = useState(false); const [searchError, setSearchError] = useState(false);
  const month = new Date().getMonth() + 1; const t = labels[language];
  useEffect(() => { try { const lang = localStorage.getItem("sea-price-language") as Language | null; if (lang && labels[lang]) setLanguage(lang); const cutoff = Date.now() - 365 * 86400000; const savedRows = JSON.parse(localStorage.getItem("sea-price-history") || "[]"); if (Array.isArray(savedRows)) setHistory(savedRows.filter((row) => row?.at && new Date(row.at).getTime() >= cutoff)); } catch {} }, []);
  function chooseLanguage(next: Language) { setLanguage(next); localStorage.setItem("sea-price-language", next); setView("main"); }
  function changeUnit(next: Unit) { setUnit(next); setAmount(next === "kg" ? 1 : 500); }
  async function calculate(event: FormEvent) { event.preventDefault(); const name = fish.trim(); if (!prices[name]) { window.alert("입력한 이름의 해산물 정보를 찾을 수 없습니다. 생선 또는 해산물 이름을 확인해 주세요."); setSearchError(true); setResult(null); return; } setSearchError(false); setLoading(true); let quote: Quote = { basePerKg: prices[name], message: "기준 소매가를 사용했어요. 인증키 설정 후 당일 경매가를 자동 반영합니다." }; try { const response = await fetch(`/api/market-price?fish=${encodeURIComponent(name)}`); if (response.ok) quote = await response.json(); } catch {} const kg = unit === "kg" ? amount : amount / 1000; const factor = origin === "wild" ? 1.12 : 1; const row: Log = { fish: name, amount, unit, origin, low: quote.basePerKg * kg * 1.2 * factor, high: quote.basePerKg * kg * 1.5 * factor, at: new Date().toLocaleString(), marketNote: quote.message }; const next = [row, ...history].slice(0,20); setResult(row); setHistory(next); localStorage.setItem("sea-price-history", JSON.stringify(next)); setLoading(false); }
  const title = tab === "price" ? t.price : tab === "season" ? t.season : tab === "history" ? t.history : t.settings;
  if (tab === "settings" && view === "language") return <main className="app"><header className="top"><div className="brand"><b>🐟 Sea Price</b></div><h1>{t.choose}</h1></header><div className="content"><section className="settings">{([['ko','한국어'],['en','English'],['ja','日本語'],['zh','中文']] as [Language,string][]).map(([code,name]) => <button key={code} className={language===code?"selected":""} onClick={()=>chooseLanguage(code)}>{name}<span>{language===code ? `✓ ${t.current}` : "›"}</span></button>)}<button onClick={()=>setView("main")}>{t.back}</button></section></div></main>;
  if (tab === "settings" && view === "report") return <main className="app"><header className="top"><div className="brand"><b>🐟 Sea Price</b></div><h1>{t.report}</h1></header><div className="content"><section className="report"><button className="back" onClick={()=>setView("main")}>{t.back}</button><textarea value={report} onChange={(e)=>setReport(e.target.value)} placeholder={t.reportHint}/><button className="primary" onClick={()=>{localStorage.setItem("sea-price-report",report);setSaved(true)}}>{t.send}</button>{saved && <p>{t.saved}</p>}</section></div></main>;
  return <main className="app"><header className="top"><div className="brand"><b>🐟 Sea Price</b><span className="pill">{month}월</span></div><h1>{title}</h1></header><div className="content">
    {tab === "price" && <><form className="form" onSubmit={calculate}><label>{t.fish}<input value={fish} onChange={(e)=>setFish(e.target.value)} placeholder={t.fishHint}/></label><label>{t.weight}<div className="toggle"><button type="button" className={unit==="kg"?"active":""} onClick={()=>changeUnit("kg")}>kg</button><button type="button" className={unit==="g"?"active":""} onClick={()=>changeUnit("g")}>g</button></div><input type="number" min="1" value={amount} onChange={(e)=>setAmount(Number(e.target.value))}/></label><label>{t.production}<div className="toggle"><button type="button" className={origin==="farmed"?"active":""} onClick={()=>setOrigin("farmed")}>{t.farmed}</button><button type="button" className={origin==="wild"?"active":""} onClick={()=>setOrigin("wild")}>{t.wild}</button></div></label><button className="primary" disabled={loading}>{loading?t.checking:t.check}</button></form>{result && <section className="result"><p className="eyebrow">{displayFish(result.fish, language)} · {result.amount}{result.unit} · {result.origin==="wild"?t.wild:t.farmed}</p><h2>{t.estimated}</h2><strong>{won(result.low)} ~ {won(result.high)}</strong><p className="market-note">{result.marketNote}</p><p>{t.market}</p><a href={`https://www.youtube.com/results?search_query=${encodeURIComponent(`${result.fish} 손질 방법`)}`} target="_blank" rel="noreferrer">{t.youtube}</a><h3>{t.notice}</h3><ol className="care">{displayCare(result.fish, language).map((item,index)=><li key={index}>{item}</li>)}</ol></section>}</>}
    {tab === "season" && <section className="season"><p className="date">{t.date} {month}월</p><div className="season-grid">{seasonal[month].map(([name,price],index)=><article key={`${name}-${index}`}><span>🐟</span><h3>{displayFish(name, language)}</h3><p>{t.seasonal}</p><strong>500g {won(price*.6)}~{won(price*.75)}<br/>1kg {won(price*1.2)}~{won(price*1.5)}</strong></article>)}</div></section>}
    {tab === "history" && <section className="history"><button className="clear" onClick={()=>{setHistory([]);localStorage.removeItem("sea-price-history")}}>{t.clear}</button><p>{t.retain}</p>{history.length?history.map((item,index)=><button key={item.at+index} onClick={()=>{setFish(item.fish);setUnit(item.unit);setAmount(item.amount);setOrigin(item.origin);setResult(item);setTab("price")}}><b>{item.fish} · {item.amount}{item.unit} · {item.origin==="wild"?t.wild:t.farmed}</b><span>{won(item.low)}~{won(item.high)}</span><small>{item.at}</small></button>):<p className="empty">{t.empty}</p>}</section>}
    {tab === "settings" && <section className="settings"><button onClick={()=>setView("language")}>🌐 {t.language}<span>›</span></button><button onClick={()=>setView("report")}>🐞 {t.report}<span>›</span></button></section>}
  </div><nav><button className={tab==="price"?"on":""} onClick={()=>setTab("price")}>₩<b>{t.price}</b></button><button className={tab==="season"?"on":""} onClick={()=>setTab("season")}>🐟<b>{t.season}</b></button><button className={tab==="history"?"on":""} onClick={()=>setTab("history")}>◷<b>{t.history}</b></button><button className={tab==="settings"?"on":""} onClick={()=>{setTab("settings");setView("main")}}>⚙<b>{t.settings}</b></button></nav></main>;
}
